### ISSUE TITLE
Please do not spam

### ISSUE THREAD

**Issue by lovell** [agily-technologies/support#3]
> Hi,
> How do you run your sprints at work? 🧐
> Would you like to improve them with some meaningful KPIs and insights on your progression? 👌
> This is why I have created Agile Sprints, a neat tool that delivers sprint reports directly to your email for free. 💪
> The project is in alpha stage, I would like your feedback on the matter.
> Check it out at https://agilesprints.io
> Let us get in touch and talk about what you need.
> Best,

Please don't scrape name and email addresses from npm and/or GitHub. Please don't send unsolicited email messages.

**Comment by kleisauke** [comment]
I received the same spam mail, so it looks like they scraped the [`package.json`](https://github.com/lovell/sharp/blob/e6a035e57571ff4261fac00c9ddd014773792ab3/package.json) from sharp.

Should I report it to `abuse@sendinblue.com`? See https://www.sendinblue.com/legal/antispampolicy/.

**Comment by lovell** [comment]
@kleisauke Yes please, and thank you for confirming my suspicion about the source.

@agilesprints Please consider donating to https://opencollective.com/libvips as an apology for wasting the time of open source maintainers.

**Comment by dherault** [comment]
Hi Lovell and Kleis,

Sorry about the spam, I won't do it again.

I bet you felt offended and I apologize for the inconvenience.
From now on I will only try to get feedback from LinkedIn and other social media sites.

Apart from the annoyance, what did you think about the product?

Thanks for the issue, it opened my eyes.
Sorry again.

Best,
David

**Comment by dherault** [comment]
By the way thanks to the cold emailing campaign we are now officially in beta! 

My main takeaways are that my product could work and that you should not run a cold emailing campaign on developers.

Sorry again 🙇‍♂️

Enjoy your day.

PS @lovell I have given $5 to libvips, not for the inconvenience but for the great tool it is! https://twitter.com/Agile_Sprints/status/1325822644680335365

**Comment by lovell** [comment]
@dherault Please can you confirm that you have **deleted** all personal details that you scraped from GitHub, including names and email addresses, and that they will never be used to send unsolicited email messages again.

**Comment by dherault** [comment]
I have not done that, at least not yet. I need the email of people who responded positively to continue working with them. For the rest, I will not send more emails. So that includes you.

**Comment by dherault** [comment]
I won't spam anymore. I have a co-founder and a user base now ❤️
